#kkk: -Dspring.profiles.active=local, dev, prd : 메인 jar파일이 java -jar 구문의 맨뒤에 있어야 함..!!
spring:
  messages:
    basename: i18n/exception
    encoding: UTF-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  application:
    name: tax-api

management:
  endpoints:
    web:
      path-mapping:
        health: healthcheck
  endpoint:
    health:
      show-details: always

tax:
#  kcbMemberKey: P09510000000
  kcbMemberKey: V43870000000
  instance: 0
  readTimeout: 5000
  coocon_token: tax-token-coocon001

jasypt:
  encryptor:
    bean: stringEncryptor